### ISSUE TITLE
windows打开，登录页手机号码区号显示+undefined。

### ISSUE THREAD

**Issue by Pinkpiglet** [AnarchStudio/gpteams#3]
![image](https://user-images.githubusercontent.com/38532706/227418077-79994991-c7bd-44ec-ac93-a40f367f7da9.png)

**Comment by suikodev** [comment]
能否提供一下运行环境信息，请问是在什么浏览器中使用的呢

**Comment by Pinkpiglet** [comment]
@suikodev  chrome浏览器     版本：111.0.5563.65
